name: Publish package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: |
          corepack enable
          yarn install
      - run: |
          yarn config set npmPublishAccess "public"
          yarn config set 'npmRegistries["//registry.npmjs.org"].npmAuthToken' "${{ secrets.NPM_TOKEN }}"
          yarn config set 'npmRegistries["//npm.pkg.github.com"].npmAuthToken' "${{ secrets.GITHUB_TOKEN }}"
      - run: |
          yarn config set npmPublishRegistry "https://registry.npmjs.org"
          yarn npm publish
      - run: |
          yarn config set npmPublishRegistry "https://npm.pkg.github.com"
          yarn npm publish
